# Generated by Django 4.2.9 on 2026-01-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a manager with access to search and profile management.', verbose_name='manager'),
        ),
    ]
