# Generated by Django 4.2.9 on 2026-01-10 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('fake_profile', 'Fake Profile'), ('inappropriate_photos', 'Inappropriate Photos'), ('harassment', 'Harassment'), ('scam', 'Scam/Fraud'), ('abusive_language', 'Abusive Language'), ('impersonation', 'Impersonation'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(max_length=2000)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('action_taken', models.CharField(blank=True, choices=[('none', 'No Action'), ('warning', 'Warning Issued'), ('photo_removed', 'Photo Removed'), ('profile_suspended', 'Profile Suspended'), ('account_banned', 'Account Banned')], default='none', max_length=30)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='profiles.profile')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to='profiles.profile')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('other', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=5000)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='feedback/%Y/%m/')),
                ('is_read', models.BooleanField(default=False)),
                ('response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_responses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
