# Generated by Django 4.2.9 on 2026-01-10 09:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='profiles.profile')),
                ('shortlisted_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_in', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'shortlist',
                'verbose_name_plural': 'shortlists',
                'ordering': ['-created_at'],
                'unique_together': {('profile', 'shortlisted_profile')},
            },
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_sent', to='profiles.profile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_received', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'pass',
                'verbose_name_plural': 'passes',
                'ordering': ['-created_at'],
                'unique_together': {('from_profile', 'to_profile')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('unmatched', 'Unmatched')], default='active', max_length=20)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('unmatched_at', models.DateTimeField(blank=True, null=True)),
                ('chat_unlocked', models.BooleanField(default=False)),
                ('chat_unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('profile1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_profile1', to='profiles.profile')),
                ('profile2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_profile2', to='profiles.profile')),
                ('unmatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmatched_connections', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'match',
                'verbose_name_plural': 'matches',
                'ordering': ['-matched_at'],
                'unique_together': {('profile1', 'profile2')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('like_type', models.CharField(choices=[('like', 'Like'), ('super_like', 'Super Like')], default='like', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message with the like', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_sent', to='profiles.profile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'like',
                'verbose_name_plural': 'likes',
                'ordering': ['-created_at'],
                'unique_together': {('from_profile', 'to_profile')},
            },
        ),
        migrations.CreateModel(
            name='InterestRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests_sent', to='profiles.profile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests_received', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'interest request',
                'verbose_name_plural': 'interest requests',
                'ordering': ['-created_at'],
                'unique_together': {('from_profile', 'to_profile')},
            },
        ),
    ]
