# Generated by Django 4.2.9 on 2026-01-10 09:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('height_cm', models.PositiveIntegerField(help_text='Height in centimeters', validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(220)])),
                ('body_type', models.CharField(blank=True, choices=[('slim', 'Slim'), ('average', 'Average'), ('athletic', 'Athletic'), ('heavy', 'Heavy')], max_length=20)),
                ('complexion', models.CharField(blank=True, choices=[('fair', 'Fair'), ('wheatish', 'Wheatish'), ('dusky', 'Dusky'), ('dark', 'Dark')], max_length=20)),
                ('marital_status', models.CharField(choices=[('never_married', 'Never Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('awaiting_divorce', 'Awaiting Divorce')], max_length=20)),
                ('religion', models.CharField(choices=[('hindu', 'Hindu'), ('muslim', 'Muslim'), ('christian', 'Christian'), ('sikh', 'Sikh'), ('buddhist', 'Buddhist'), ('jain', 'Jain'), ('parsi', 'Parsi'), ('jewish', 'Jewish'), ('other', 'Other')], max_length=20)),
                ('caste', models.CharField(blank=True, max_length=100)),
                ('sub_caste', models.CharField(blank=True, max_length=100)),
                ('mother_tongue', models.CharField(max_length=50)),
                ('education', models.CharField(choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('doctorate', 'Doctorate/PhD'), ('professional', 'Professional Degree (CA, MBBS, etc.)')], max_length=50)),
                ('education_detail', models.CharField(blank=True, help_text='Specific degree/college', max_length=200)),
                ('profession', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('annual_income', models.CharField(choices=[('0-3', 'Less than 3 Lakhs'), ('3-5', '3-5 Lakhs'), ('5-10', '5-10 Lakhs'), ('10-15', '10-15 Lakhs'), ('15-25', '15-25 Lakhs'), ('25-50', '25-50 Lakhs'), ('50-75', '50-75 Lakhs'), ('75-100', '75 Lakhs - 1 Crore'), ('100+', 'More than 1 Crore')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('siblings', models.CharField(blank=True, help_text='e.g., 1 elder brother, 1 younger sister', max_length=200)),
                ('family_type', models.CharField(blank=True, choices=[('joint', 'Joint Family'), ('nuclear', 'Nuclear Family')], max_length=20)),
                ('family_values', models.CharField(blank=True, choices=[('traditional', 'Traditional'), ('moderate', 'Moderate'), ('liberal', 'Liberal')], max_length=20)),
                ('diet', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-Vegetarian'), ('eggetarian', 'Eggetarian'), ('vegan', 'Vegan'), ('jain', 'Jain (No Onion/Garlic)')], max_length=20)),
                ('smoking', models.CharField(choices=[('no', 'No'), ('occasionally', 'Occasionally'), ('yes', 'Yes')], default='no', max_length=20)),
                ('drinking', models.CharField(choices=[('no', 'No'), ('occasionally', 'Occasionally'), ('yes', 'Yes')], default='no', max_length=20)),
                ('manglik', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partial'), ('dont_know', "Don't Know")], max_length=20)),
                ('star_sign', models.CharField(blank=True, max_length=50)),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=100)),
                ('about_me', models.TextField(help_text='Tell us about yourself', max_length=2000)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('profile_views', models.PositiveIntegerField(default=0)),
                ('profile_score', models.PositiveIntegerField(default=0, help_text='Profile completeness score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='profile_photos/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='profile_photos/thumbnails/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'profile photo',
                'verbose_name_plural': 'profile photos',
                'ordering': ['display_order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age_from', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(70)])),
                ('age_to', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(70)])),
                ('height_from', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(220)])),
                ('height_to', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(220)])),
                ('marital_status', models.JSONField(default=list, help_text='List of acceptable marital statuses')),
                ('religion', models.JSONField(default=list, help_text='List of acceptable religions')),
                ('caste', models.JSONField(blank=True, default=list, help_text='List of acceptable castes')),
                ('caste_no_bar', models.BooleanField(default=False)),
                ('education', models.JSONField(default=list, help_text='List of acceptable education levels')),
                ('profession', models.JSONField(blank=True, default=list, help_text='List of acceptable professions')),
                ('income_from', models.CharField(blank=True, max_length=20)),
                ('income_to', models.CharField(blank=True, max_length=20)),
                ('country', models.JSONField(blank=True, default=list)),
                ('state', models.JSONField(blank=True, default=list)),
                ('city', models.JSONField(blank=True, default=list)),
                ('mother_tongue', models.JSONField(blank=True, default=list)),
                ('diet', models.JSONField(blank=True, default=list)),
                ('smoking', models.JSONField(blank=True, default=list)),
                ('drinking', models.JSONField(blank=True, default=list)),
                ('manglik', models.JSONField(blank=True, default=list)),
                ('additional_preferences', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_preferences', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'partner preference',
                'verbose_name_plural': 'partner preferences',
            },
        ),
        migrations.CreateModel(
            name='GovernmentID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID')], max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('document_front', models.ImageField(upload_to='verification_docs/%Y/%m/')),
                ('document_back', models.ImageField(blank=True, upload_to='verification_docs/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='government_ids', to='profiles.profile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_ids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'government ID',
                'verbose_name_plural': 'government IDs',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_received', to='profiles.profile')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles_viewed', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'profile view',
                'verbose_name_plural': 'profile views',
                'ordering': ['-viewed_at'],
                'unique_together': {('viewer', 'viewed_profile', 'viewed_at')},
            },
        ),
        migrations.CreateModel(
            name='BlockedProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='profiles.profile')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_profiles', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'blocked profile',
                'verbose_name_plural': 'blocked profiles',
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
