# Generated by Django 6.0.1 on 2026-01-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='complexion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mother_tongue',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sub_caste',
        ),
    ]
